const Data = [
    {
      id: 1,
      category: "Education",
      icon: "uil-graduation-cap",
      year: "2021 - present",
      title: "M.Sc. Information Technology Degree",
      subtitle: 'RJ College',
      desc: "Lorem ipsum dolor sit amet quo ei simul congue exerciad nec admodum perfecto.",
    },
    {
      id: 2,
      category: "Education",
      icon: "uil-graduation-cap",
      year: "2017 - 2020",
      title: "B.Sc. Information Technology Degree",
      subtitle: 'KJ Somaiya',
      desc: "Lorem ipsum dolor sit amet quo ei simul congue exerciad nec admodum perfecto.",
    },
    {
      id: 3,
      category: "Education",
      icon: "uil-graduation-cap",
      year: "2016 - 2017",
      title: "Senior Secondary (XII) - Science Stream",
      subtitle: 'S. N. B.',
      desc: "Lorem ipsum dolor sit amet quo ei simul congue exerciad nec admodum perfecto.",
    },
    {
      id: 4,
      category: "Freelancing",
      icon: "uil-briefcase-alt",
      year: "2021 - present",
      title: "Web Designer",
      subtitle: 'JMM InfoTech',
      desc: "Lorem ipsum dolor sit amet quo ei simul congue exerciad nec admodum perfecto.",
    },
    {
      id: 5,
      category: "Freelancing",
      icon: "uil-briefcase-alt",
      year: "2021 - 2022",
      title: "Flutter Development",
      subtitle: 'JMM InfoTech',
      desc: "Lorem ipsum dolor sit amet quo ei simul congue exerciad nec admodum perfecto.",
    },
    {
      id: 6,
      category: "Freelancing",
      icon: "uil-briefcase-alt",
      year: "2021 - 2022",
      title: "Back-End Developer",
      subtitle: 'JMM InfoTech',
      desc: "Lorem ipsum dolor sit amet quo ei simul congue exerciad nec admodum perfecto.",
    },
    {
        id: 7,
        category: "Education",
        icon: "uil-graduation-cap",
        year: "2014 - 2015",
        title: "Secondary (X) - Hindi Medium",
        subtitle: 'Y. S. K. V.',
        desc: "Lorem ipsum dolor sit amet quo ei simul congue exerciad nec admodum perfecto.",
      },
      {
        id: 5,
        category: "Freelancing",
        icon: "uil-briefcase-alt",
        year: "2018 - 2020",
        title: "Front-End Developer",
        subtitle: 'JMM InfoTech',
        desc: "Lorem ipsum dolor sit amet quo ei simul congue exerciad nec admodum perfecto.",
      }
  ];

export default Data